### ISSUE TITLE
vc_redisit.exe @ 0 byte/s

### ISSUE THREAD

**Issue by ptorrent** [voicemxil/TS-Starter-Pack#10]
Hello!

THanks for your awesome work... I'm using the web installer and still waiting download for vc_redist since 2 hours. Currently vc_redist.exe is about 3MB, how long do I've to wait for it ?

Is there a different way to get this Binary file ?

**Comment by voicemxil** [comment]
> Hello!
> 
> 
> 
> THanks for your awesome work... I'm using the web installer and still waiting download for vc_redist since 2 hours. Currently vc_redist.exe is about 3MB, how long do I've to wait for it ?
> 
> 
> 
> Is there a different way to get this Binary file ?

You don't "have to wait," there's evidently a connection issue on your end so you can just skip/close out the installer with task manager and download it from Microsoft separately (x64 visual c++ redistributable)

**Comment by ptorrent** [comment]
Hi again, I was finally able to get it. Everything is wokring fine. Sound, display on win 11. Perfect.

THanks for your awesome job again !
