### ISSUE TITLE
32-bit version?

### ISSUE THREAD

**Issue by vanyasem** [voicemxil/TS-Starter-Pack#5]
Would it be possible to have a 32-bit version of the installer? For use on Windows XP SP 3 x86

**Comment by mintalien** [comment]
> Would it be possible to have a 32-bit version of the installer? For use on Windows XP SP 3 x86

The Widescreen Patcher included is 64-bit only, which was the main reason for it being 64-bit only. I can make a 32-bit version, but it would have the patcher removed.

**Comment by vanyasem** [comment]
@mintalien that would be great. It's okay for it to not have a widescreen patch. Thank you

**Comment by Akoi89** [comment]
https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/1.24.0-legacy

This works with 32-bit/windows xp.

**Comment by vanyasem** [comment]
@voicemxil thank you for adding 32 bit support in [v15](https://github.com/voicemxil/TS-Starter-Pack/releases/tag/v15)!
